export interface Airport {
  id: string;
  iata: string;
  name: string;
  city: string;
  countryId: string;
}

export const WELL_KNOWN_AIRPORTS: Airport[] = [
  { id: 'es-mad', iata: 'MAD', name: 'Adolfo Suarez Madrid-Barajas Airport', city: 'Madrid', countryId: 'ES' },
  { id: 'es-bcn', iata: 'BCN', name: 'Barcelona-El Prat Airport', city: 'Barcelona', countryId: 'ES' },
  { id: 'es-pmi', iata: 'PMI', name: 'Palma de Mallorca Airport', city: 'Palma', countryId: 'ES' },
  { id: 'es-agp', iata: 'AGP', name: 'Malaga-Costa del Sol Airport', city: 'Malaga', countryId: 'ES' },
  { id: 'es-alc', iata: 'ALC', name: 'Alicante-Elche Miguel Hernandez Airport', city: 'Alicante', countryId: 'ES' },
  { id: 'es-lpa', iata: 'LPA', name: 'Gran Canaria Airport', city: 'Las Palmas', countryId: 'ES' },
  { id: 'es-tfs', iata: 'TFS', name: 'Tenerife South Airport', city: 'Tenerife', countryId: 'ES' },
  { id: 'es-vlc', iata: 'VLC', name: 'Valencia Airport', city: 'Valencia', countryId: 'ES' },
  { id: 'es-ibz', iata: 'IBZ', name: 'Ibiza Airport', city: 'Ibiza', countryId: 'ES' },
  { id: 'es-svq', iata: 'SVQ', name: 'Seville Airport', city: 'Seville', countryId: 'ES' },
  { id: 'es-bio', iata: 'BIO', name: 'Bilbao Airport', city: 'Bilbao', countryId: 'ES' },
  { id: 'es-ace', iata: 'ACE', name: 'Lanzarote Airport', city: 'Lanzarote', countryId: 'ES' },
  { id: 'es-tfn', iata: 'TFN', name: 'Tenerife North-Ciudad de La Laguna Airport', city: 'Tenerife', countryId: 'ES' },
  { id: 'es-fue', iata: 'FUE', name: 'Fuerteventura Airport', city: 'Fuerteventura', countryId: 'ES' },
  { id: 'es-scq', iata: 'SCQ', name: 'Santiago-Rosalia de Castro Airport', city: 'Santiago de Compostela', countryId: 'ES' },
  { id: 'es-mah', iata: 'MAH', name: 'Menorca Airport', city: 'Menorca', countryId: 'ES' },
  { id: 'es-gro', iata: 'GRO', name: 'Girona-Costa Brava Airport', city: 'Girona', countryId: 'ES' },
  { id: 'es-zaz', iata: 'ZAZ', name: 'Zaragoza Airport', city: 'Zaragoza', countryId: 'ES' },
  { id: 'es-ovd', iata: 'OVD', name: 'Asturias Airport', city: 'Asturias', countryId: 'ES' },
  { id: 'es-vgo', iata: 'VGO', name: 'Vigo Airport', city: 'Vigo', countryId: 'ES' },

  { id: 'gb-lhr', iata: 'LHR', name: 'Heathrow Airport', city: 'London', countryId: 'GB' },
  { id: 'gb-lgw', iata: 'LGW', name: 'Gatwick Airport', city: 'London', countryId: 'GB' },
  { id: 'gb-man', iata: 'MAN', name: 'Manchester Airport', city: 'Manchester', countryId: 'GB' },
  { id: 'gb-stn', iata: 'STN', name: 'Stansted Airport', city: 'London', countryId: 'GB' },
  { id: 'gb-ltn', iata: 'LTN', name: 'Luton Airport', city: 'London', countryId: 'GB' },
  { id: 'gb-edi', iata: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh', countryId: 'GB' },
  { id: 'gb-bhx', iata: 'BHX', name: 'Birmingham Airport', city: 'Birmingham', countryId: 'GB' },
  { id: 'gb-gla', iata: 'GLA', name: 'Glasgow Airport', city: 'Glasgow', countryId: 'GB' },
  { id: 'gb-brs', iata: 'BRS', name: 'Bristol Airport', city: 'Bristol', countryId: 'GB' },
  { id: 'gb-ncl', iata: 'NCL', name: 'Newcastle Airport', city: 'Newcastle', countryId: 'GB' },
  { id: 'gb-bfs', iata: 'BFS', name: 'Belfast International Airport', city: 'Belfast', countryId: 'GB' },
  { id: 'gb-bhd', iata: 'BHD', name: 'George Best Belfast City Airport', city: 'Belfast', countryId: 'GB' },
  { id: 'gb-lcy', iata: 'LCY', name: 'London City Airport', city: 'London', countryId: 'GB' },
  { id: 'gb-lba', iata: 'LBA', name: 'Leeds Bradford Airport', city: 'Leeds', countryId: 'GB' },
  { id: 'gb-lpl', iata: 'LPL', name: 'Liverpool John Lennon Airport', city: 'Liverpool', countryId: 'GB' },
  { id: 'gb-ema', iata: 'EMA', name: 'East Midlands Airport', city: 'Nottingham', countryId: 'GB' },
  { id: 'gb-abz', iata: 'ABZ', name: 'Aberdeen International Airport', city: 'Aberdeen', countryId: 'GB' },
  { id: 'gb-cwl', iata: 'CWL', name: 'Cardiff Airport', city: 'Cardiff', countryId: 'GB' },
  { id: 'gb-sou', iata: 'SOU', name: 'Southampton Airport', city: 'Southampton', countryId: 'GB' },
  { id: 'gb-inv', iata: 'INV', name: 'Inverness Airport', city: 'Inverness', countryId: 'GB' },

  { id: 'fr-cdg', iata: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris', countryId: 'FR' },
  { id: 'fr-ory', iata: 'ORY', name: 'Paris Orly Airport', city: 'Paris', countryId: 'FR' },
  { id: 'fr-nce', iata: 'NCE', name: 'Nice Cote d Azur Airport', city: 'Nice', countryId: 'FR' },
  { id: 'fr-lys', iata: 'LYS', name: 'Lyon-Saint Exupery Airport', city: 'Lyon', countryId: 'FR' },
  { id: 'fr-mrs', iata: 'MRS', name: 'Marseille Provence Airport', city: 'Marseille', countryId: 'FR' },
  { id: 'fr-tls', iata: 'TLS', name: 'Toulouse-Blagnac Airport', city: 'Toulouse', countryId: 'FR' },
  { id: 'fr-bod', iata: 'BOD', name: 'Bordeaux-Merignac Airport', city: 'Bordeaux', countryId: 'FR' },
  { id: 'fr-nte', iata: 'NTE', name: 'Nantes Atlantique Airport', city: 'Nantes', countryId: 'FR' },
  { id: 'fr-bva', iata: 'BVA', name: 'Paris Beauvais Airport', city: 'Paris', countryId: 'FR' },
  { id: 'fr-mpl', iata: 'MPL', name: 'Montpellier-Mediterranee Airport', city: 'Montpellier', countryId: 'FR' },
  { id: 'fr-lil', iata: 'LIL', name: 'Lille Airport', city: 'Lille', countryId: 'FR' },
  { id: 'fr-sxb', iata: 'SXB', name: 'Strasbourg Airport', city: 'Strasbourg', countryId: 'FR' },

  { id: 'it-fco', iata: 'FCO', name: 'Leonardo da Vinci-Fiumicino Airport', city: 'Rome', countryId: 'IT' },
  { id: 'it-mxp', iata: 'MXP', name: 'Milan Malpensa Airport', city: 'Milan', countryId: 'IT' },
  { id: 'it-berg', iata: 'BGY', name: 'Milan Bergamo Airport', city: 'Bergamo', countryId: 'IT' },
  { id: 'it-vce', iata: 'VCE', name: 'Venice Marco Polo Airport', city: 'Venice', countryId: 'IT' },
  { id: 'it-nap', iata: 'NAP', name: 'Naples International Airport', city: 'Naples', countryId: 'IT' },
  { id: 'it-lin', iata: 'LIN', name: 'Milan Linate Airport', city: 'Milan', countryId: 'IT' },
  { id: 'it-cia', iata: 'CIA', name: 'Rome Ciampino Airport', city: 'Rome', countryId: 'IT' },
  { id: 'it-cta', iata: 'CTA', name: 'Catania-Fontanarossa Airport', city: 'Catania', countryId: 'IT' },
  { id: 'it-blq', iata: 'BLQ', name: 'Bologna Guglielmo Marconi Airport', city: 'Bologna', countryId: 'IT' },
  { id: 'it-pmo', iata: 'PMO', name: 'Palermo Falcone Borsellino Airport', city: 'Palermo', countryId: 'IT' },
  { id: 'it-psa', iata: 'PSA', name: 'Pisa International Airport', city: 'Pisa', countryId: 'IT' },
  { id: 'it-flr', iata: 'FLR', name: 'Florence Airport', city: 'Florence', countryId: 'IT' },
  { id: 'it-bri', iata: 'BRI', name: 'Bari Karol Wojtyla Airport', city: 'Bari', countryId: 'IT' },
  { id: 'it-trn', iata: 'TRN', name: 'Turin Airport', city: 'Turin', countryId: 'IT' },

  { id: 'us-atl', iata: 'ATL', name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta', countryId: 'US' },
  { id: 'us-lax', iata: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', countryId: 'US' },
  { id: 'us-ord', iata: 'ORD', name: 'Chicago O Hare International Airport', city: 'Chicago', countryId: 'US' },
  { id: 'us-dfw', iata: 'DFW', name: 'Dallas Fort Worth International Airport', city: 'Dallas', countryId: 'US' },
  { id: 'us-den', iata: 'DEN', name: 'Denver International Airport', city: 'Denver', countryId: 'US' },
  { id: 'us-jfk', iata: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', countryId: 'US' },
  { id: 'us-sfo', iata: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', countryId: 'US' },
  { id: 'us-sea', iata: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', countryId: 'US' },
  { id: 'us-mia', iata: 'MIA', name: 'Miami International Airport', city: 'Miami', countryId: 'US' },
  { id: 'us-bos', iata: 'BOS', name: 'Boston Logan International Airport', city: 'Boston', countryId: 'US' },
  { id: 'us-las', iata: 'LAS', name: 'Harry Reid International Airport', city: 'Las Vegas', countryId: 'US' },
  { id: 'us-mco', iata: 'MCO', name: 'Orlando International Airport', city: 'Orlando', countryId: 'US' },
  { id: 'us-clt', iata: 'CLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', countryId: 'US' },
  { id: 'us-phx', iata: 'PHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', countryId: 'US' },
  { id: 'us-iah', iata: 'IAH', name: 'George Bush Intercontinental Airport', city: 'Houston', countryId: 'US' },
  { id: 'us-ewr', iata: 'EWR', name: 'Newark Liberty International Airport', city: 'Newark', countryId: 'US' },
  { id: 'us-msy', iata: 'MSY', name: 'Louis Armstrong New Orleans International Airport', city: 'New Orleans', countryId: 'US' },
  { id: 'us-fll', iata: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport', city: 'Fort Lauderdale', countryId: 'US' },
  { id: 'us-dtw', iata: 'DTW', name: 'Detroit Metropolitan Wayne County Airport', city: 'Detroit', countryId: 'US' },
  { id: 'us-phl', iata: 'PHL', name: 'Philadelphia International Airport', city: 'Philadelphia', countryId: 'US' },
  { id: 'us-iad', iata: 'IAD', name: 'Washington Dulles International Airport', city: 'Washington', countryId: 'US' },
  { id: 'us-dca', iata: 'DCA', name: 'Ronald Reagan Washington National Airport', city: 'Washington', countryId: 'US' },
  { id: 'us-bwi', iata: 'BWI', name: 'Baltimore Washington International Airport', city: 'Baltimore', countryId: 'US' },
  { id: 'us-san', iata: 'SAN', name: 'San Diego International Airport', city: 'San Diego', countryId: 'US' },
  { id: 'us-tpa', iata: 'TPA', name: 'Tampa International Airport', city: 'Tampa', countryId: 'US' },
  { id: 'us-aus', iata: 'AUS', name: 'Austin-Bergstrom International Airport', city: 'Austin', countryId: 'US' },
  { id: 'us-bna', iata: 'BNA', name: 'Nashville International Airport', city: 'Nashville', countryId: 'US' },
  { id: 'us-pdx', iata: 'PDX', name: 'Portland International Airport', city: 'Portland', countryId: 'US' },
  { id: 'us-hnl', iata: 'HNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu', countryId: 'US' },
  { id: 'us-slc', iata: 'SLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', countryId: 'US' },

  { id: 'de-fra', iata: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', countryId: 'DE' },
  { id: 'de-muc', iata: 'MUC', name: 'Munich Airport', city: 'Munich', countryId: 'DE' },
  { id: 'de-ber', iata: 'BER', name: 'Berlin Brandenburg Airport', city: 'Berlin', countryId: 'DE' },
  { id: 'de-dus', iata: 'DUS', name: 'Dusseldorf Airport', city: 'Dusseldorf', countryId: 'DE' },
  { id: 'de-ham', iata: 'HAM', name: 'Hamburg Airport', city: 'Hamburg', countryId: 'DE' },
  { id: 'de-cgn', iata: 'CGN', name: 'Cologne Bonn Airport', city: 'Cologne', countryId: 'DE' },
  { id: 'de-str', iata: 'STR', name: 'Stuttgart Airport', city: 'Stuttgart', countryId: 'DE' },
  { id: 'de-nue', iata: 'NUE', name: 'Nuremberg Airport', city: 'Nuremberg', countryId: 'DE' },
  { id: 'de-haj', iata: 'HAJ', name: 'Hannover Airport', city: 'Hannover', countryId: 'DE' },
  { id: 'de-bre', iata: 'BRE', name: 'Bremen Airport', city: 'Bremen', countryId: 'DE' },
  { id: 'de-dtm', iata: 'DTM', name: 'Dortmund Airport', city: 'Dortmund', countryId: 'DE' },
  { id: 'de-fkb', iata: 'FKB', name: 'Karlsruhe Baden-Baden Airport', city: 'Baden-Baden', countryId: 'DE' },
  { id: 'de-lej', iata: 'LEJ', name: 'Leipzig Halle Airport', city: 'Leipzig', countryId: 'DE' },
  { id: 'de-drs', iata: 'DRS', name: 'Dresden Airport', city: 'Dresden', countryId: 'DE' },
  { id: 'de-fmm', iata: 'FMM', name: 'Memmingen Airport', city: 'Memmingen', countryId: 'DE' },

  { id: 'nl-ams', iata: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', countryId: 'NL' },
  { id: 'nl-ein', iata: 'EIN', name: 'Eindhoven Airport', city: 'Eindhoven', countryId: 'NL' },
  { id: 'nl-rtm', iata: 'RTM', name: 'Rotterdam The Hague Airport', city: 'Rotterdam', countryId: 'NL' },
  { id: 'pt-lis', iata: 'LIS', name: 'Lisbon Airport', city: 'Lisbon', countryId: 'PT' },
  { id: 'pt-opo', iata: 'OPO', name: 'Porto Airport', city: 'Porto', countryId: 'PT' },
  { id: 'pt-fao', iata: 'FAO', name: 'Faro Airport', city: 'Faro', countryId: 'PT' },
  { id: 'pt-fnc', iata: 'FNC', name: 'Madeira Airport', city: 'Madeira', countryId: 'PT' },
  { id: 'pt-pdl', iata: 'PDL', name: 'Ponta Delgada Airport', city: 'Ponta Delgada', countryId: 'PT' },
  { id: 'pt-ter', iata: 'TER', name: 'Lajes Airport', city: 'Terceira', countryId: 'PT' },
  { id: 'ie-dub', iata: 'DUB', name: 'Dublin Airport', city: 'Dublin', countryId: 'IE' },
  { id: 'ie-ork', iata: 'ORK', name: 'Cork Airport', city: 'Cork', countryId: 'IE' },
  { id: 'ie-snn', iata: 'SNN', name: 'Shannon Airport', city: 'Shannon', countryId: 'IE' },
  { id: 'ie-noc', iata: 'NOC', name: 'Ireland West Airport Knock', city: 'Knock', countryId: 'IE' },
  { id: 'ch-zrh', iata: 'ZRH', name: 'Zurich Airport', city: 'Zurich', countryId: 'CH' },
  { id: 'ch-gva', iata: 'GVA', name: 'Geneva Airport', city: 'Geneva', countryId: 'CH' },
  { id: 'ch-bsl', iata: 'BSL', name: 'EuroAirport Basel Mulhouse Freiburg', city: 'Basel', countryId: 'CH' },

  { id: 'be-bru', iata: 'BRU', name: 'Brussels Airport', city: 'Brussels', countryId: 'BE' },
  { id: 'be-crl', iata: 'CRL', name: 'Brussels South Charleroi Airport', city: 'Charleroi', countryId: 'BE' },
  { id: 'at-vie', iata: 'VIE', name: 'Vienna International Airport', city: 'Vienna', countryId: 'AT' },
  { id: 'at-szg', iata: 'SZG', name: 'Salzburg Airport', city: 'Salzburg', countryId: 'AT' },
  { id: 'dk-cph', iata: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', countryId: 'DK' },
  { id: 'dk-bll', iata: 'BLL', name: 'Billund Airport', city: 'Billund', countryId: 'DK' },
  { id: 'dk-aal', iata: 'AAL', name: 'Aalborg Airport', city: 'Aalborg', countryId: 'DK' },
  { id: 'se-arn', iata: 'ARN', name: 'Stockholm Arlanda Airport', city: 'Stockholm', countryId: 'SE' },
  { id: 'se-got', iata: 'GOT', name: 'Goteborg Landvetter Airport', city: 'Gothenburg', countryId: 'SE' },
  { id: 'se-bma', iata: 'BMA', name: 'Stockholm Bromma Airport', city: 'Stockholm', countryId: 'SE' },
  { id: 'se-mmx', iata: 'MMX', name: 'Malmo Airport', city: 'Malmo', countryId: 'SE' },
  { id: 'no-osl', iata: 'OSL', name: 'Oslo Airport', city: 'Oslo', countryId: 'NO' },
  { id: 'no-bgo', iata: 'BGO', name: 'Bergen Airport', city: 'Bergen', countryId: 'NO' },
  { id: 'no-svg', iata: 'SVG', name: 'Stavanger Airport', city: 'Stavanger', countryId: 'NO' },
  { id: 'no-trd', iata: 'TRD', name: 'Trondheim Airport', city: 'Trondheim', countryId: 'NO' },
  { id: 'fi-hel', iata: 'HEL', name: 'Helsinki Airport', city: 'Helsinki', countryId: 'FI' },
  { id: 'fi-oul', iata: 'OUL', name: 'Oulu Airport', city: 'Oulu', countryId: 'FI' },
  { id: 'fi-tku', iata: 'TKU', name: 'Turku Airport', city: 'Turku', countryId: 'FI' },
  { id: 'pl-waw', iata: 'WAW', name: 'Warsaw Chopin Airport', city: 'Warsaw', countryId: 'PL' },
  { id: 'pl-krk', iata: 'KRK', name: 'Krakow John Paul II International Airport', city: 'Krakow', countryId: 'PL' },
  { id: 'pl-gdn', iata: 'GDN', name: 'Gdansk Lech Walesa Airport', city: 'Gdansk', countryId: 'PL' },
  { id: 'pl-wro', iata: 'WRO', name: 'Wroclaw Airport', city: 'Wroclaw', countryId: 'PL' },
  { id: 'pl-ktw', iata: 'KTW', name: 'Katowice Airport', city: 'Katowice', countryId: 'PL' },
  { id: 'pl-pozn', iata: 'POZ', name: 'Poznan-Lawica Airport', city: 'Poznan', countryId: 'PL' },
  { id: 'cz-prg', iata: 'PRG', name: 'Vaclav Havel Airport Prague', city: 'Prague', countryId: 'CZ' },
  { id: 'cz-brq', iata: 'BRQ', name: 'Brno-Turany Airport', city: 'Brno', countryId: 'CZ' },
  { id: 'hu-bud', iata: 'BUD', name: 'Budapest Ferenc Liszt International Airport', city: 'Budapest', countryId: 'HU' },
  { id: 'gr-ath', iata: 'ATH', name: 'Athens International Airport', city: 'Athens', countryId: 'GR' },
  { id: 'gr-skg', iata: 'SKG', name: 'Thessaloniki Airport', city: 'Thessaloniki', countryId: 'GR' },
  { id: 'gr-her', iata: 'HER', name: 'Heraklion International Airport', city: 'Heraklion', countryId: 'GR' },
  { id: 'gr-rho', iata: 'RHO', name: 'Rhodes International Airport', city: 'Rhodes', countryId: 'GR' },
  { id: 'gr-cfu', iata: 'CFU', name: 'Corfu International Airport', city: 'Corfu', countryId: 'GR' },
  { id: 'gr-jtr', iata: 'JTR', name: 'Santorini Airport', city: 'Santorini', countryId: 'GR' },
  { id: 'hr-zag', iata: 'ZAG', name: 'Zagreb Airport', city: 'Zagreb', countryId: 'HR' },
  { id: 'hr-spu', iata: 'SPU', name: 'Split Airport', city: 'Split', countryId: 'HR' },
  { id: 'hr-dbv', iata: 'DBV', name: 'Dubrovnik Airport', city: 'Dubrovnik', countryId: 'HR' },
  { id: 'ro-otp', iata: 'OTP', name: 'Henri Coanda International Airport', city: 'Bucharest', countryId: 'RO' },
  { id: 'bg-sof', iata: 'SOF', name: 'Sofia Airport', city: 'Sofia', countryId: 'BG' },
  { id: 'rs-beg', iata: 'BEG', name: 'Belgrade Nikola Tesla Airport', city: 'Belgrade', countryId: 'RS' },
  { id: 'si-lju', iata: 'LJU', name: 'Ljubljana Joze Pucnik Airport', city: 'Ljubljana', countryId: 'SI' },
  { id: 'sk-bts', iata: 'BTS', name: 'Bratislava Airport', city: 'Bratislava', countryId: 'SK' },
  { id: 'lt-vno', iata: 'VNO', name: 'Vilnius Airport', city: 'Vilnius', countryId: 'LT' },
  { id: 'lv-rix', iata: 'RIX', name: 'Riga International Airport', city: 'Riga', countryId: 'LV' },
  { id: 'ee-tll', iata: 'TLL', name: 'Tallinn Airport', city: 'Tallinn', countryId: 'EE' },
  { id: 'is-kef', iata: 'KEF', name: 'Keflavik International Airport', city: 'Reykjavik', countryId: 'IS' },
  { id: 'mt-mla', iata: 'MLA', name: 'Malta International Airport', city: 'Malta', countryId: 'MT' },
  { id: 'cy-lca', iata: 'LCA', name: 'Larnaca International Airport', city: 'Larnaca', countryId: 'CY' },
  { id: 'cy-pfo', iata: 'PFO', name: 'Paphos International Airport', city: 'Paphos', countryId: 'CY' },
  { id: 'lu-lux', iata: 'LUX', name: 'Luxembourg Airport', city: 'Luxembourg', countryId: 'LU' },

  { id: 'ae-dxb', iata: 'DXB', name: 'Dubai International Airport', city: 'Dubai', countryId: 'AE' },
  { id: 'ae-auh', iata: 'AUH', name: 'Zayed International Airport', city: 'Abu Dhabi', countryId: 'AE' },
  { id: 'sa-jed', iata: 'JED', name: 'King Abdulaziz International Airport', city: 'Jeddah', countryId: 'SA' },
  { id: 'sa-ruh', iata: 'RUH', name: 'King Khalid International Airport', city: 'Riyadh', countryId: 'SA' },
  { id: 'kw-kwi', iata: 'KWI', name: 'Kuwait International Airport', city: 'Kuwait City', countryId: 'KW' },
  { id: 'bh-bah', iata: 'BAH', name: 'Bahrain International Airport', city: 'Manama', countryId: 'BH' },
  { id: 'om-mct', iata: 'MCT', name: 'Muscat International Airport', city: 'Muscat', countryId: 'OM' },
  { id: 'tr-ist', iata: 'IST', name: 'Istanbul Airport', city: 'Istanbul', countryId: 'TR' },
  { id: 'tr-saw', iata: 'SAW', name: 'Istanbul Sabiha Gokcen International Airport', city: 'Istanbul', countryId: 'TR' },
  { id: 'tr-ayt', iata: 'AYT', name: 'Antalya Airport', city: 'Antalya', countryId: 'TR' },
  { id: 'tr-esb', iata: 'ESB', name: 'Ankara Esenboga Airport', city: 'Ankara', countryId: 'TR' },
  { id: 'qa-doh', iata: 'DOH', name: 'Hamad International Airport', city: 'Doha', countryId: 'QA' },
  { id: 'il-tlv', iata: 'TLV', name: 'Ben Gurion Airport', city: 'Tel Aviv', countryId: 'IL' },
  { id: 'jo-amm', iata: 'AMM', name: 'Queen Alia International Airport', city: 'Amman', countryId: 'JO' },
  { id: 'lb-bey', iata: 'BEY', name: 'Beirut-Rafic Hariri International Airport', city: 'Beirut', countryId: 'LB' },
  { id: 'sg-sin', iata: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore', countryId: 'SG' },
  { id: 'my-kul', iata: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', countryId: 'MY' },
  { id: 'id-cgk', iata: 'CGK', name: 'Soekarno-Hatta International Airport', city: 'Jakarta', countryId: 'ID' },
  { id: 'id-dps', iata: 'DPS', name: 'Ngurah Rai International Airport', city: 'Bali', countryId: 'ID' },
  { id: 'ph-mnl', iata: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila', countryId: 'PH' },
  { id: 'vn-sgn', iata: 'SGN', name: 'Tan Son Nhat International Airport', city: 'Ho Chi Minh City', countryId: 'VN' },
  { id: 'vn-han', iata: 'HAN', name: 'Noi Bai International Airport', city: 'Hanoi', countryId: 'VN' },
  { id: 'th-dmk', iata: 'DMK', name: 'Don Mueang International Airport', city: 'Bangkok', countryId: 'TH' },
  { id: 'th-hkt', iata: 'HKT', name: 'Phuket International Airport', city: 'Phuket', countryId: 'TH' },
  { id: 'jp-hnd', iata: 'HND', name: 'Tokyo Haneda Airport', city: 'Tokyo', countryId: 'JP' },
  { id: 'jp-nrt', iata: 'NRT', name: 'Narita International Airport', city: 'Tokyo', countryId: 'JP' },
  { id: 'jp-kix', iata: 'KIX', name: 'Kansai International Airport', city: 'Osaka', countryId: 'JP' },
  { id: 'jp-cts', iata: 'CTS', name: 'New Chitose Airport', city: 'Sapporo', countryId: 'JP' },
  { id: 'cn-pek', iata: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', countryId: 'CN' },
  { id: 'cn-pkx', iata: 'PKX', name: 'Beijing Daxing International Airport', city: 'Beijing', countryId: 'CN' },
  { id: 'cn-pvg', iata: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai', countryId: 'CN' },
  { id: 'cn-sha', iata: 'SHA', name: 'Shanghai Hongqiao International Airport', city: 'Shanghai', countryId: 'CN' },
  { id: 'cn-can', iata: 'CAN', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou', countryId: 'CN' },
  { id: 'cn-szx', iata: 'SZX', name: 'Shenzhen Baoan International Airport', city: 'Shenzhen', countryId: 'CN' },
  { id: 'hk-hkg', iata: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong', countryId: 'HK' },
  { id: 'tw-tpe', iata: 'TPE', name: 'Taiwan Taoyuan International Airport', city: 'Taipei', countryId: 'TW' },
  { id: 'th-bkk', iata: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', countryId: 'TH' },
  { id: 'kr-icn', iata: 'ICN', name: 'Incheon International Airport', city: 'Seoul', countryId: 'KR' },
  { id: 'kr-gmp', iata: 'GMP', name: 'Gimpo International Airport', city: 'Seoul', countryId: 'KR' },
  { id: 'in-del', iata: 'DEL', name: 'Indira Gandhi International Airport', city: 'Delhi', countryId: 'IN' },
  { id: 'in-bom', iata: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai', countryId: 'IN' },
  { id: 'in-blr', iata: 'BLR', name: 'Kempegowda International Airport', city: 'Bengaluru', countryId: 'IN' },
  { id: 'in-maa', iata: 'MAA', name: 'Chennai International Airport', city: 'Chennai', countryId: 'IN' },
  { id: 'in-hyd', iata: 'HYD', name: 'Rajiv Gandhi International Airport', city: 'Hyderabad', countryId: 'IN' },
  { id: 'in-ccu', iata: 'CCU', name: 'Netaji Subhas Chandra Bose International Airport', city: 'Kolkata', countryId: 'IN' },
  { id: 'in-cok', iata: 'COK', name: 'Cochin International Airport', city: 'Kochi', countryId: 'IN' },
  { id: 'in-goi', iata: 'GOI', name: 'Goa Dabolim Airport', city: 'Goa', countryId: 'IN' },
  { id: 'in-amd', iata: 'AMD', name: 'Sardar Vallabhbhai Patel International Airport', city: 'Ahmedabad', countryId: 'IN' },
  { id: 'pk-khi', iata: 'KHI', name: 'Jinnah International Airport', city: 'Karachi', countryId: 'PK' },
  { id: 'pk-lhe', iata: 'LHE', name: 'Allama Iqbal International Airport', city: 'Lahore', countryId: 'PK' },
  { id: 'pk-isb', iata: 'ISB', name: 'Islamabad International Airport', city: 'Islamabad', countryId: 'PK' },
  { id: 'bd-dac', iata: 'DAC', name: 'Hazrat Shahjalal International Airport', city: 'Dhaka', countryId: 'BD' },
  { id: 'lk-cmb', iata: 'CMB', name: 'Bandaranaike International Airport', city: 'Colombo', countryId: 'LK' },
  { id: 'np-ktm', iata: 'KTM', name: 'Tribhuvan International Airport', city: 'Kathmandu', countryId: 'NP' },
  { id: 'au-syd', iata: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney', countryId: 'AU' },
  { id: 'au-mel', iata: 'MEL', name: 'Melbourne Airport', city: 'Melbourne', countryId: 'AU' },
  { id: 'au-bne', iata: 'BNE', name: 'Brisbane Airport', city: 'Brisbane', countryId: 'AU' },
  { id: 'au-per', iata: 'PER', name: 'Perth Airport', city: 'Perth', countryId: 'AU' },
  { id: 'au-adl', iata: 'ADL', name: 'Adelaide Airport', city: 'Adelaide', countryId: 'AU' },
  { id: 'nz-akl', iata: 'AKL', name: 'Auckland Airport', city: 'Auckland', countryId: 'NZ' },
  { id: 'nz-chc', iata: 'CHC', name: 'Christchurch Airport', city: 'Christchurch', countryId: 'NZ' },
  { id: 'nz-wlg', iata: 'WLG', name: 'Wellington Airport', city: 'Wellington', countryId: 'NZ' },
  { id: 'fj-nan', iata: 'NAN', name: 'Nadi International Airport', city: 'Nadi', countryId: 'FJ' },
  { id: 'ca-yyz', iata: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', countryId: 'CA' },
  { id: 'ca-yvr', iata: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver', countryId: 'CA' },
  { id: 'ca-yul', iata: 'YUL', name: 'Montreal-Trudeau International Airport', city: 'Montreal', countryId: 'CA' },
  { id: 'ca-yyc', iata: 'YYC', name: 'Calgary International Airport', city: 'Calgary', countryId: 'CA' },
  { id: 'ca-yeg', iata: 'YEG', name: 'Edmonton International Airport', city: 'Edmonton', countryId: 'CA' },
  { id: 'ca-yow', iata: 'YOW', name: 'Ottawa International Airport', city: 'Ottawa', countryId: 'CA' },
  { id: 'ca-yhz', iata: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', countryId: 'CA' },
  { id: 'ca-ywg', iata: 'YWG', name: 'Winnipeg Richardson International Airport', city: 'Winnipeg', countryId: 'CA' },
  { id: 'ca-yqb', iata: 'YQB', name: 'Quebec City Jean Lesage International Airport', city: 'Quebec City', countryId: 'CA' },
  { id: 'mx-mex', iata: 'MEX', name: 'Mexico City International Airport', city: 'Mexico City', countryId: 'MX' },
  { id: 'mx-cun', iata: 'CUN', name: 'Cancun International Airport', city: 'Cancun', countryId: 'MX' },
  { id: 'mx-gdl', iata: 'GDL', name: 'Guadalajara International Airport', city: 'Guadalajara', countryId: 'MX' },
  { id: 'mx-mty', iata: 'MTY', name: 'Monterrey International Airport', city: 'Monterrey', countryId: 'MX' },
  { id: 'mx-pvr', iata: 'PVR', name: 'Puerto Vallarta International Airport', city: 'Puerto Vallarta', countryId: 'MX' },
  { id: 'mx-sjd', iata: 'SJD', name: 'Los Cabos International Airport', city: 'San Jose del Cabo', countryId: 'MX' },
  { id: 'do-sdq', iata: 'SDQ', name: 'Las Americas International Airport', city: 'Santo Domingo', countryId: 'DO' },
  { id: 'do-puj', iata: 'PUJ', name: 'Punta Cana International Airport', city: 'Punta Cana', countryId: 'DO' },
  { id: 'jm-mbj', iata: 'MBJ', name: 'Sangster International Airport', city: 'Montego Bay', countryId: 'JM' },
  { id: 'jm-kin', iata: 'KIN', name: 'Norman Manley International Airport', city: 'Kingston', countryId: 'JM' },
  { id: 'bs-nas', iata: 'NAS', name: 'Lynden Pindling International Airport', city: 'Nassau', countryId: 'BS' },
  { id: 'bb-bgi', iata: 'BGI', name: 'Grantley Adams International Airport', city: 'Bridgetown', countryId: 'BB' },
  { id: 'tt-pos', iata: 'POS', name: 'Piarco International Airport', city: 'Port of Spain', countryId: 'TT' },
  { id: 'cu-hav', iata: 'HAV', name: 'Jose Marti International Airport', city: 'Havana', countryId: 'CU' },
  { id: 'br-gru', iata: 'GRU', name: 'Sao Paulo-Guarulhos International Airport', city: 'Sao Paulo', countryId: 'BR' },
  { id: 'br-gig', iata: 'GIG', name: 'Rio de Janeiro-Galeao International Airport', city: 'Rio de Janeiro', countryId: 'BR' },
  { id: 'br-cgh', iata: 'CGH', name: 'Sao Paulo-Congonhas Airport', city: 'Sao Paulo', countryId: 'BR' },
  { id: 'ar-eze', iata: 'EZE', name: 'Ministro Pistarini International Airport', city: 'Buenos Aires', countryId: 'AR' },
  { id: 'ar-aep', iata: 'AEP', name: 'Jorge Newbery Airfield', city: 'Buenos Aires', countryId: 'AR' },
  { id: 'cl-scl', iata: 'SCL', name: 'Arturo Merino Benitez International Airport', city: 'Santiago', countryId: 'CL' },
  { id: 'co-bog', iata: 'BOG', name: 'El Dorado International Airport', city: 'Bogota', countryId: 'CO' },
  { id: 'pe-lim', iata: 'LIM', name: 'Jorge Chavez International Airport', city: 'Lima', countryId: 'PE' },
  { id: 'pa-pty', iata: 'PTY', name: 'Tocumen International Airport', city: 'Panama City', countryId: 'PA' },
  { id: 'cr-sjo', iata: 'SJO', name: 'Juan Santamaria International Airport', city: 'San Jose', countryId: 'CR' },
  { id: 'ec-uio', iata: 'UIO', name: 'Mariscal Sucre International Airport', city: 'Quito', countryId: 'EC' },
  { id: 'ec-gye', iata: 'GYE', name: 'Jose Joaquin de Olmedo International Airport', city: 'Guayaquil', countryId: 'EC' },
  { id: 'uy-mvd', iata: 'MVD', name: 'Carrasco International Airport', city: 'Montevideo', countryId: 'UY' },
  { id: 'py-asu', iata: 'ASU', name: 'Silvio Pettirossi International Airport', city: 'Asuncion', countryId: 'PY' },
  { id: 'bo-vvi', iata: 'VVI', name: 'Viru Viru International Airport', city: 'Santa Cruz', countryId: 'BO' },
  { id: 'za-jnb', iata: 'JNB', name: 'O. R. Tambo International Airport', city: 'Johannesburg', countryId: 'ZA' },
  { id: 'za-cpt', iata: 'CPT', name: 'Cape Town International Airport', city: 'Cape Town', countryId: 'ZA' },
  { id: 'eg-cai', iata: 'CAI', name: 'Cairo International Airport', city: 'Cairo', countryId: 'EG' },
  { id: 'ma-cmn', iata: 'CMN', name: 'Mohammed V International Airport', city: 'Casablanca', countryId: 'MA' },
  { id: 'ma-rak', iata: 'RAK', name: 'Marrakesh Menara Airport', city: 'Marrakesh', countryId: 'MA' },
  { id: 'ma-aga', iata: 'AGA', name: 'Agadir Al Massira Airport', city: 'Agadir', countryId: 'MA' },
  { id: 'tn-tun', iata: 'TUN', name: 'Tunis-Carthage International Airport', city: 'Tunis', countryId: 'TN' },
  { id: 'dz-alg', iata: 'ALG', name: 'Houari Boumediene Airport', city: 'Algiers', countryId: 'DZ' },
  { id: 'ke-nbo', iata: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi', countryId: 'KE' },
  { id: 'et-add', iata: 'ADD', name: 'Addis Ababa Bole International Airport', city: 'Addis Ababa', countryId: 'ET' },
  { id: 'ng-los', iata: 'LOS', name: 'Murtala Muhammed International Airport', city: 'Lagos', countryId: 'NG' },
  { id: 'gh-acc', iata: 'ACC', name: 'Kotoka International Airport', city: 'Accra', countryId: 'GH' },
  { id: 'tz-dar', iata: 'DAR', name: 'Julius Nyerere International Airport', city: 'Dar es Salaam', countryId: 'TZ' },
];

export function formatAirportLabel(airport: Airport): string {
  return `${airport.iata} - ${airport.name}`;
}
